name: scp files
on: [push]
jobs:

  copy:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: 45.79.123.122
        username: "anurag"
        password: "Anurag@!234"
        port: 22
        source: "./*"
        target: "php"
      
#   deploy:
#     runs-on: self-hosted
#     steps:
#       - name: Hello world
#         shell: bash
#         run: |
#           cd ~
#           cd /var/www/html/php/
#           git status
#           git pull
#          git pull origin
#          ./moveFiles.sh 
      
#   copy:
#     runs-on: self-hosted
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v2
#     - name: Deployment
#       uses: appleboy/ssh-action@master
#       with:
#         #host: 172.105.34.69
#         #username: "user1"
#         #key: ${{ secrets.SSH_PRIVATE_KEY }}
#         scripts: |
#           cd ~
#           mv php /var/www/html/
     
